### ISSUE TITLE
Epic: Internationalization (i18n), lokalization (l10n) and related tools

### ISSUE THREAD

**Issue by openscript** [Couchers-org/couchers#1576]
As we are an international community languages are important to help couchers to access and use the platform. Not only translating the content, but also showing the time, dates or other localizable content will help for a good user experience. This is an epic which helps to organize the requirements to i18n and l10n.

- [x] Couchers-org/couchers#1577 
- [ ] Define process to create a new locale
- [ ] Set up i18n/l10n platform
- [ ] Determine users preferred locale
- [ ] Select locale and save selection
- [ ] Save locale selection in backend

**Comment by lucaslcode** [comment]
Hi @openscript, how is this going?

**Comment by openscript** [comment]
Hi Lucas
Recently I didn't have much time to work on this, but I will get on it this week.

**Comment by lucaslcode** [comment]
closed in favour of Couchers-org/couchers#4152
