### ISSUE TITLE
Host Requests/Chat megaissue

### ISSUE THREAD

**Issue by lucaslcode** [Couchers-org/couchers#4196]
~~These will be refactored.~~ (postponed) At the same time, these issues should be solved:

- [x] Couchers-org/couchers#1481 
- [ ] Couchers-org/couchers#1449 
- [ ] Couchers-org/couchers#1376 
- [ ] Couchers-org/couchers#1183 
- [ ] Couchers-org/couchers#1087 
- [ ] Couchers-org/couchers#937 
- [ ] Couchers-org/couchers#1652 
- [x] Couchers-org/couchers#1675

**Comment by lucaslcode** [comment]
@wbruntra here is the megaissue I failed to find in the meeting. All these were planned for the refactor, but since that's not a priority now, the good value ones should be done now.

**Comment by nabramow** [comment]
@bakeiro it looks like all of these are done? Should we close this one?

**Comment by bakeiro** [comment]
@nabramow yeah my idea was to create a milestone for this, so I know what's done what's missing, but I didn't have time lately 😅

**Comment by nabramow** [comment]
@bakeiro No worries should I close it then, or it makes sense to keep in Backlog?

**Comment by bakeiro** [comment]
@nabramow good question actually, lucas doesn't in Couchers anymore (at least not like before) idk, I guess both things are fine? 😅

**Comment by aapeliv** [comment]
Let's close this one and we'll keep track of newer changes elsewhere
